name = "CFEM_AM"
uuid = "368ce5e7-e9ef-4586-bf20-c950fa62d9d9"
authors = ["Acme Corp"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
